DROP TABLE IF EXISTS "ReferencePost" CASCADE;
DROP TABLE IF EXISTS "AppSetting" CASCADE;
DROP TABLE IF EXISTS "TopicRecommendation" CASCADE;
DROP TABLE IF EXISTS "PostFeedback" CASCADE;
DROP TABLE IF EXISTS "SelectedPost" CASCADE;
DROP TABLE IF EXISTS "GeneratedPost" CASCADE;
DROP TABLE IF EXISTS "BrandContextSection" CASCADE;
DROP TABLE IF EXISTS "TalkingPoint" CASCADE;
DROP TABLE IF EXISTS "Topic" CASCADE;
DROP TABLE IF EXISTS "Campaign" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Persona" CASCADE;

DROP TYPE IF EXISTS "GeneratedPostStatus";
DROP TYPE IF EXISTS "TopicStatus";
DROP TYPE IF EXISTS "Channel";
DROP TYPE IF EXISTS "UserRole";
